### ISSUE TITLE
Ruby 2.2.0: setup.rb:284: warning: duplicated key at line 285 ignored: "bin-dir"

### ISSUE THREAD

**Issue by Moter8** [cinchrb/cinch#187]
```
carstenh@carstenh-vm-kubu ~/g/rbot (master)> ruby -v
ruby 2.2.0p0 (2014-12-25 revision 49005) [x86_64-linux]
carstenh@carstenh-vm-kubu ~/g/rbot (master)> ruby setup.rb 
setup.rb:284: warning: duplicated key at line 285 ignored: "bin-dir"
setup.rb:789:in `load_rbconfig': uninitialized constant Config (NameError)
        from setup.rb:769:in `invoke'
        from setup.rb:1579:in `<main>'
```

**Comment by dominikh** [comment]
There is no `setup.rb` file in the Cinch project, and "rbot" sounds like the Rbot project, not Cinch.

**Comment by Moter8** [comment]
Woops, got confused with so many tabs open, sorry!
